# Generated by Django 3.2.8 on 2022-07-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('homework_json', models.JSONField()),
                ('last_date', models.DateField()),
                ('batch', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
